const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Behaviors.Tween,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetWebFont,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastStatusCode,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Browser.Acts.Reload
	];
};
self.C3_JsPropNameTable = [
	{TopPipe: 0},
	{TopCapPipe: 0},
	{GapBlock: 0},
	{BottomCapPipe: 0},
	{BottomPipe: 0},
	{CapXSpawn: 0},
	{PipeXSpawn: 0},
	{BillboardSpawnPoint: 0},
	{BlimpSpawnPoint: 0},
	{Blimp: 0},
	{AJAX_Status: 0},
	{GOText: 0},
	{HasilScore: 0},
	{ScoreText: 0},
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{Keyboard: 0},
	{PlayBtn: 0},
	{AJAX: 0},
	{ParallaxBackground: 0},
	{BG_Env: 0},
	{BG_Road: 0},
	{BG_Sky: 0},
	{BG_Skyline: 0},
	{Billboard: 0},
	{Tween: 0},
	{Blimps: 0},
	{BlackBackdrop: 0},
	{MulaiBtn: 0},
	{ScreenLogo: 0},
	{LightFlash: 0},
	{Flash: 0},
	{tabrakan: 0},
	{BlackdropGO: 0},
	{Platform: 0},
	{Bird: 0},
	{Scored: 0},
	{DestroyOutsideLayout: 0},
	{BottomPipes: 0},
	{TopPipes: 0},
	{UIScore: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Background: 0},
	{New_BG_Sky: 0},
	{New_BG_Skyline: 0},
	{Audio: 0},
	{MainMenuTxt: 0},
	{LeaderBoard: 0},
	{Shadow: 0},
	{SecondsPerObstacle: 0},
	{JumpStrength: 0},
	{ScrollSpeed: 0},
	{GapController: 0},
	{Score: 0},
	{roadHeight: 0},
	{capPipeHeight: 0},
	{minPipeHeight: 0},
	{GameStage: 0},
	{ID_user: 0},
	{ID_game: 0},
	{SpeedMultiplier: 0},
	{LevelUpScore: 0},
	{JarakBillboard: 0},
	{JarakBlimp: 0},
	{SkySpeed: 0},
	{SkylineSpeed: 0},
	{EnviSpeed: 0},
	{RoadSpeed: 0},
	{maxSpawnGapCoorY: 0},
	{availableSpawnGapCoorY: 0},
	{topPipeHeight: 0},
	{bottomPipeHeight: 0},
	{JarakPipa: 0}
];

self.InstanceType = {
	TopPipe: class extends self.ISpriteInstance {},
	TopCapPipe: class extends self.ISpriteInstance {},
	GapBlock: class extends self.ISpriteInstance {},
	BottomCapPipe: class extends self.ISpriteInstance {},
	BottomPipe: class extends self.ISpriteInstance {},
	CapXSpawn: class extends self.ISpriteInstance {},
	PipeXSpawn: class extends self.ISpriteInstance {},
	BillboardSpawnPoint: class extends self.ISpriteInstance {},
	BlimpSpawnPoint: class extends self.ISpriteInstance {},
	Blimp: class extends self.ISpriteInstance {},
	AJAX_Status: class extends self.ITextInstance {},
	GOText: class extends self.ITextInstance {},
	HasilScore: class extends self.ITextInstance {},
	ScoreText: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	PlayBtn: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	ParallaxBackground: class extends self.ISpriteInstance {},
	BG_Env: class extends self.ISpriteInstance {},
	BG_Road: class extends self.ISpriteInstance {},
	BG_Sky: class extends self.ISpriteInstance {},
	BG_Skyline: class extends self.ISpriteInstance {},
	Billboard: class extends self.ISpriteInstance {},
	Blimps: class extends self.ISpriteInstance {},
	BlackBackdrop: class extends self.ISpriteInstance {},
	MulaiBtn: class extends self.ISpriteInstance {},
	ScreenLogo: class extends self.ISpriteInstance {},
	LightFlash: class extends self.ISpriteInstance {},
	Flash: class extends self.ISpriteInstance {},
	tabrakan: class extends self.ISpriteInstance {},
	BlackdropGO: class extends self.ISpriteInstance {},
	Bird: class extends self.ISpriteInstance {},
	BottomPipes: class extends self.ISpriteInstance {},
	TopPipes: class extends self.ISpriteInstance {},
	UIScore: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ISpriteInstance {},
	New_BG_Sky: class extends self.ISpriteInstance {},
	New_BG_Skyline: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	MainMenuTxt: class extends self.ITextInstance {},
	LeaderBoard: class extends self.ISpriteInstance {},
	Shadow: class extends self.ISpriteInstance {}
}