const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Platform,
		C3.Behaviors.destroy,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetWebFont,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{Pipe: 0},
	{CapPipe: 0},
	{GapBlock: 0},
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{Asset: 0},
	{Asset2: 0},
	{Background: 0},
	{Platform: 0},
	{Bird: 0},
	{Scored: 0},
	{DestroyOutsideLayout: 0},
	{BottomPipe: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{TopPipe: 0},
	{ScoreText: 0},
	{PlayBtn: 0},
	{Family1: 0},
	{SecondsPerObstacle: 0},
	{JumpStrength: 0},
	{ScrollSpeed: 0},
	{GapController: 0},
	{Score: 0},
	{roadHeight: 0},
	{capPipeHeight: 0},
	{minPipeHeight: 0},
	{maxSpawnGapCoorY: 0},
	{availableSpawnGapCoorY: 0},
	{topPipeHeight: 0}
];

self.InstanceType = {
	Pipe: class extends self.ISpriteInstance {},
	CapPipe: class extends self.ISpriteInstance {},
	GapBlock: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Asset: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Bird: class extends self.ISpriteInstance {},
	BottomPipe: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TopPipe: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	PlayBtn: class extends self.IButtonInstance {},
	Family1: class extends self.ISpriteInstance {}
}